# Generated by Django 5.0.4 on 2024-04-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Введите название бренда', max_length=100, verbose_name='Бренд')),
                ('model', models.CharField(help_text='Введите модель', max_length=100, verbose_name='Модель')),
                ('year', models.IntegerField(blank=True, help_text='Введите год выпуска', null=True)),
                ('color', models.CharField(help_text='Введите цвет автомобиля', max_length=50, verbose_name='Цвет автомобиля')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
